### PR TITLE
GH-128 Move initialize of removeExistingWar out of afterEvaluate

### LINKED ISSUE #128: createDockerFile#removeExistingWar config modified after evaluation
**Steps to reproduce:**
Apply the `eu.xenit.docker-alfresco` plugin and adapt the `createDockerFile` configuration as follows:
``` Java
createDockerFile {
    removeExistingWar = false
    checkAlfrescoVersion =  false
}
```

**Expected behavior:**
The existing war is not removed.

**Actual behavior:** 
The existing war gets removed. 

**Root cause:** 
The `createDockerFile#removeExistingWar` is modified after evaluation by the `DockerAlfrescoPlugin`:
https://github.com/xenit-eu/alfresco-docker-gradle-plugin/blob/1928fbc3b7701f684cbc4059c392d56bd02f24b7/src/main/java/eu/xenit/gradle/docker/alfresco/DockerAlfrescoPlugin.java#L77

### PR DESCRIPTION
**Pull request by kerkhofsd**
Fixes #128

### CODE REVIEW

**Comment by kerkhofsd** [comment]
> Can you add a testcase for this too?
> 
> If you can't create a good testcase, I can add one myself later (But I'll keep this PR open then to remind me)

@vierbergenlars 
I did a quick try, but got stuck and therefore didn't add one. I got stuck because I didn't find a way to do assertions on a project after it is configured using the Gradle test kit. 

If you can give me some pointers that can help for testing this scenario, I can add one.

**Comment by vierbergenlars** [comment]
> I did a quick try, but got stuck and therefore didn't add one. I got stuck because I didn't find a way to do assertions on a project after it is configured using the Gradle test kit.

Here is one way to do an assert: https://github.com/xenit-eu/alfresco-docker-gradle-plugin/blob/9d6ab09162584fabe259cfd6030a457d41d8972b/src/integrationTest/reproductions/issue-97/build.gradle#L53

However, I don't think this check is a good fit for integration tests, so you can add a unittest instead.

Something simple where you create a project, apply and configure the plugin and task, then call `project.evaluate()` and check the results afterwards.

https://github.com/xenit-eu/alfresco-docker-gradle-plugin/blob/1e725056c983d07fe7c95ac25274ea5768180a1c/src/test/java/eu/xenit/gradle/docker/alfresco/DockerAlfrescoPluginTest.java#L99-L114

**Comment by kerkhofsd** [comment]
@vierbergenlars good pointers, thanks! Added a unit test.

**Comment by vierbergenlars** [comment]
Looks good. Then it will be in the next release :tada:

**Pull request merged**
